default:
  listenAddr: ":6180"
  webSocketListenAddr: ""
  JWTSecret: "kubemanage"
  expireTime: 10

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "chenteng"
  name: "kubemanage"
  maxOpenConns: 100
  maxLifetime: 20
  maxIdleConns: 10

log:
  level: "debug"   ## 日志等级
  filename: "kubemanage.log"  # 日志文件位置
  max_size: 200    # 日志文件最大大小(MB)
  max_age: 30      # 保留旧日志文件的最大天数
  max_backups: 7   # 最大保留日志个数